name: Build
on:
    pull_request:
        paths: ['**/*.md', 'book.json', 'package.json']
    push: #for test in feat/#33. todo: delete
        branches: ['feat/#33']
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 'lts/*'
                  cache: 'npm'

            - name: Install and Build
              run: |
                  npm install
                  npx honkit build
