name: Deploy Main Documentation

on:
    push:
        branches: [main]
        paths: ['**/*.md', 'book.json', 'package.json', 'SUMMARY.md']
    workflow_run:
        workflows: ['Update SUMMARY.md']
        types: [completed]
        branches: [main]

jobs:
    deploy-main:
        runs-on: ubuntu-latest

        permissions:
            contents: write
            pages: write
            id-token: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 'lts/*'
                  cache: 'npm'

            - name: Build documentation
              run: |
                  npm install
                  npx honkit build

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./_book
                  commit_message: 'Deploy: ${{ github.sha }}'
